version: '3.8'

services:
  makeshort-backend:
    container_name: "makeshort-bot"
    image: "makeshort-bot:latest"
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - CONFIG_PATH=./config/dev.yml
